services:
  - type: web
    name: recipeshare
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: recipeshare-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: recipeshare-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: recipeshare-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: recipeshare-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: recipeshare-db
          property: password
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false

databases:
  - name: recipeshare-db
    databaseName: recipeshare
    user: recipeshare_user
    plan: free
